application.data-dir: ~/assets
server.port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DB_PROTO:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_trashbank}?serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:admin}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.${DB_DIALECT:MySQL57Dialect}
  messages.basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
